# Taken from https://github.com/husky/husky/blob/8cd932ac230b87ba0ce59b75908b759f4065a6c1/husky_navigation/config/costmap_exploration.yaml
# https://husarion.com/tutorials/ros-tutorials/8-unknown-environment-exploration/
track_unknown_space: true
global_frame: map
rolling_window: false
resolution: 0.05
robot_base_frame: base_link
robot_radius: 0.20
transform_tolerance: 5.0
update_frequency: 5.0
publish_frequency: 5.0

plugins:
- {name: static,            type: "costmap_2d::StaticLayer"}   # for global map
- {name: explore_boundary,  type: "frontier_exploration::BoundedExploreLayer"}
#Can disable sensor layer if gmapping is fast enough to update scans
# - {name: sensor,            type: "costmap_2d::ObstacleLayer"}
- {name: inflation,         type: "costmap_2d::InflationLayer"}

static:
  map_topic: /map
  subscribe_to_updates: true

explore_boundary:
  resize_to_boundary: false
  frontier_travel_point: middle
  explore_clear_space: false


sensor:
  observation_sources: scan left_bump right_bump
  scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, obstacle_range: 2.5, raytrace_range: 3.0}
  left_bump: {data_type: PointCloud2, topic: /bump_sensor_left, marking: true, clearing: true}
  right_bump: {data_type: PointCloud2, topic: /bump_sensor_right, marking: true, clearing: true}


inflation:
  inflation_radius: 0.5
